version: "3"

services: 
  app:
    build:
      context: ./src
      dockerfile: Dockerfile.dev
    environment:
      DEBUG: "yes"
      DB_NAME: app
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/app
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local